### ISSUE TITLE
Gradle could not get unknown property ALIAS_JKS_PASSWORD

### ISSUE THREAD

**Issue by manic-coder** [brunodea/udacity-finalproj#1]
Hey man, I saw your post on reddit and decided to help contribute to the app :)

I'm also a fairly new Android dev, and don't know much about gradle. I've imported the project into Android Studio and I'm getting this error:

`Error:(16, 0) Could not get unknown property 'ALIAS_JKS_PASSWORD' for SigningConfig_Decorated{name=release, storeFile=null, storePassword=null, keyAlias=nevertoolate, keyPassword=null, storeType=null, v1SigningEnabled=true, v2SigningEnabled=true} of type com.android.build.gradle.internal.dsl.SigningConfig.`

Any ideas what to do?

**Comment by brunodea** [comment]
First of all, thank you very much!

Yes, you are having this issue because of https://github.com/brunodea/udacity-finalproj/blob/master/app/build.gradle#L16
There are some variables that need to be declared in your gradle.properties file (you can create it in case it doesn't exist):
ALIAS_JKS_PASSWORD=<keystore alias password>
APK_JKS_PASSWORD=<keystore passowrd>
GOOGLE_API_KEY=<your google api key>
REDDIT_ACCOUNT=<your reddit account name>
REDDIT_KEY=<your reddit client key>

In order to compile without a signature, you can simply set the jks variables to whatever. I think it should work, of course it won't in case you try to compile a signed version.

For the app to work, you definitely need the other three variables.
the google api key you can create here: https://console.developers.google.com/apis/credentials (don't forget to enable the places and geolocation apis for android in the "Libraries" menu.

The reddit account is the name of some account of yours.
The reddit key you can in reddit get by going to preferences -> apps -> click on "Are you a developer? create an app", (https://i.imgur.com/ILMeklr.png -- use the Client ID).

I think that's it. Please let me know in case something goes wrong.

**Comment by brunodea** [comment]
I just realized the README was missing that information, sorry for that.

I already edited it, but I think maybe signing stuff shouldn't be open sourced here, idk. We'll see.

**Comment by brunodea** [comment]
This app is changing constantly, so my first comment is already outdated lol.
It's better to just keep looking at the README, I shall not forget to fix it when necessary.

I am closing this, thanks!
